"""
Configuration for NEPSE Data Scraper
"""

# Known NEPSE listed companies (symbol -> full name)
# You can extend this list or use the company_list_scraper to auto-discover
COMPANIES = {
    # Commercial Banks
    "ACLBSL": "Aarambha Chautari Laghubitta Bittiya Sanstha Limited",
"ADBL": "Agricultural Development Bank Limited",
"AHL": "Asian Hydropower Limited",
"AHPC": "Arun Valley Hydropower Development Co. Ltd.",
"AKJCL": "Ankhu Khola Jalvidhyut Company Ltd",
"AKPL": "Arun Kabeli Power Ltd.",
"ALBSL": "Asha Laghubitta Bittiya Sanstha Ltd",
"ALICL": "Asian Life Insurance Co. Limited",
"ANLB": "Aatmanirbhar Laghubitta Bittiya Sanstha Limited",
"API": "Api Power Company Ltd.",
"AVYAN": "Aviyan Laghubitta Bittiya Sanstha Limited",
"BANDIPUR": "Bandipur Cablecar and Tourism Limited",
"BARUN": "Barun Hydropower Co. Ltd.",
"BBC": "Bishal Bazar Company Limited",
"BEDC": "Bhugol Energy Development Company Limited",
"BFC": "Best Finance Company Ltd.",
"BGWT": "Bhagawati Hydropower Development Company Limited",
"BHCL": "Bikash Hydropower Company Limited",
"BHDC": "Bindhyabasini Hydropower Development Company Limited",
"BHL": "Balephi Hydropower Limited",
"BHPL": "Barahi Hydropower Public Limited",
"BNHC": "Buddha Bhumi Nepal Hydropower Company Limited",
"BNL": "Bottlers Nepal (Balaju) Limited",
"BNT": "Bottlers Nepal (Terai) Limited",
"BPCL": "Butwal Power Company Limited",
"BUNGAL": "Bungal Hydro Limited",
"CBBL": "Chhimek Laghubitta Bittiya Sanstha Limited",
"CFCL": "Central Finance Co. Ltd.",
"CGH": "Chandragiri Hills Limited",
"CHCL": "Chilime Hydropower Company Limited",
"CHDC": "CEDB Holdings Limited",
"CHL": "Chhyangdi Hydropower Ltd.",
"CIT": "Citizen Investment Trust",
"CITY": "City Hotel Limited",
"CKHL": "Chirkhwa Hydropower Limited",
"CLI": "Citizen Life Insurance Company Limited",
"CORBL": "Corporate Development Bank Limited",
"CREST": "Crest Micro Life Insurance Limited",
"CYCL": "CYC Nepal Laghubitta Bittiya Sanstha Limited",
"CZBIL": "Citizens Bank International Limited",
"DDBL": "Deprosc Laghubitta Bittiya Sanstha Limited",
"DHEL": "Daramkhola Hydro Energy Limited",
"DHPL": "Dibyashwori Hydropower Ltd.",
"DLBS": "Dhaulagiri Laghubitta Bittiya Sanstha Limited",
"DOLTI": "Dolti Power Company Limited",
"DORDI": "Dordi Khola Jal Bidyut Company Limited",
"EBL": "Everest Bank Limited",
"EDBL": "Excel Development Bank Ltd.",
"EHPL": "Eastern Hydropower Limited",
"ENL": "Emerging Nepal Limited",
"FMDBL": "First Micro Finance Laghubitta Bittiya Sanstha Limited",
"FOWAD": "Forward Microfinance Laghubitta Bittiya Sanstha Limited",
"GBBL": "Garima Bikas Bank Limited",
"GBIME": "Global IME Bank Limited",
"GBLBS": "Grameen Bikas Laghubitta Bittiya Sanstha Ltd.",
"GCIL": "Ghorahi Cement Industry Limited",
"GFCL": "Goodwill Finance Limited",
"GHL": "Ghalemdi Hydro Limited",
"GILB": "Global IME Laghubitta Bittiya Sanstha Ltd.",
"GLBSL": "Gurans Laghubitta Bittiya Sanstha Limited",
"GLH": "GreenLife Hydropower Limited",
"GMFBS": "Ganapati Laghubitta Bittiya Sanstha Limited",
"GMFIL": "Guheshowori Merchant Bank & Finance Co. Ltd.",
"GMLI": "Guardian Micro Life Insurance Limited",
"GRDBL": "Green Development Bank Ltd.",
"GUFL": "Gurkhas Finance Ltd.",
"GVL": "Green Ventures Limited",
"HATHY": "Hathway Investment Nepal Limited",
"HBL": "Himalayan Bank Limited",
"HDHPC": "Himal Dolakha Hydropower Company Limited",
"HDL": "Himalayan Distillery Limited",
"HEI": "Himalayan Everest Insurance Limited",
"HFIN": "Hotel Forest Inn Limited",
"HHL": "Himalayan Hydropower Limited",
"HIDCL": "Hydorelectricity Investment and Development Company Ltd",
"HIMSTAR": "Him Star Urja Company Limited",
"HLBSL": "Himalayan Laghubitta Bittiya Sanstha Limited",
"HLI": "Himalayan Life Insurance Limited",
"HPPL": "Himalayan Power Partner Ltd.",
"HRL": "Himalayan Reinsurance Limited",
"HURJA": "Himalaya Urja Bikas Company Limited",
"ICFC": "ICFC Finance Limited",
"IGI": "IGI Prudential insurance Limited",
"IHL": "Ingwa Hydropower Limited",
"ILBS": "Infinity Laghubitta Bittiya Sanstha Limited",
"ILI": "IME Life Insurance Company Limited",
"JBBL": "Jyoti Bikas Bank Limited",
"JBLB": "Jeevan Bikas Laghubitta Bittya Sanstha Ltd",
"JFL": "Janaki Finance Company Limited",
"JHAPA": "Jhapa Energy Limited",
"JOSHI": "Joshi Hydropower Development Company Ltd",
"JSLBB": "Janautthan Samudayic Laghubitta Bittya Sanstha Limited",
"KBL": "Kumari Bank Limited",
"KBSH": "Kutheli Bukhari Small Hydropower Limited",
"KDL": "Kalinchowk Darshan Limited",
"KKHC": "Khanikhola Hydropower Co. Ltd.",
"KMCDB": "Kalika Laghubitta Bittiya Sanstha Ltd",
"KPCL": "Kalika power Company Ltd",
"KSBBL": "Kamana Sewa Bikas Bank Limited",
"LBBL": "Lumbini Bikas Bank Ltd.",
"LEC": "Liberty Energy Company Limited",
"LICN": "Life Insurance Corporation (Nepal) Limited",
"LLBS": "Laxmi Laghubitta Bittiya Sanstha Ltd.",
"LSL": "Laxmi Sunrise Bank Limited",
"MABEL": "Mabilung Energy Limited",
"MAKAR": "Makar Jitumaya Suri Hydropower Limited",
"MANDU": "Mandu Hydropower Limited",
"MATRI": "Matribhumi Lagubitta Bittiya Sanstha Limited",
"MBJC": "Madhya Bhotekoshi Jalavidyut Company Limited",
"MBL": "Machhapuchhre Bank Limited",
"MCHL": "Menchhiyam Hydropower Limited",
"MDB": "Miteri Development Bank Limited",
"MEHL": "Manakamana Engineering Hydropower Limited",
"MEL": "Modi Energy Limited",
"MEN": "Mountain Energy Nepal Limited",
"MERO": "Mero Microfinance Bittiya Sanstha Ltd.",
"MFIL": "Manjushree Finance Ltd.",
"MHCL": "Molung Hydropower Company Limited",
"MHL": "Mandakini Hydropower Limited",
"MHNL": "Mountain Hydro Nepal Limited",
"MKCL": "Muktinath Krishi Company Limited",
"MKHC": "Maya Khola Hydropower Company Limited",
"MKHL": "Mai Khola Hydropower Limited",
"MKJC": "Mailung Khola Jal Vidhyut Company Limited",
"MLBBL": "Mithila LaghuBitta Bittiya Sanstha Limited",
"MLBL": "Mahalaxmi Bikas Bank Ltd.",
"MLBS": "Manushi Laghubitta Bittiya Sanstha Limited",
"MLBSL": "Mahila Lagubitta Bittiya Sanstha Limited",
"MMKJL": "Mathillo Mailun Khola Jalvidhyut Limited",
"MNBBL": "Muktinath Bikas Bank Ltd.",
"MPFL": "Multipurpose Finance Company Limited",
"MSHL": "Mid Solu Hydropower Limited",
"MSLB": "Mahuli Laghubitta Bittiya Sanstha Limited",
"NABBC": "Narayani Development Bank Limited",
"NABIL": "Nabil Bank Limited",
"NADEP": "Nadep Laghubittiya bittya Sanstha Ltd.",
"NBL": "Nepal Bank Limited",
"NESDO": "NESDO Sambridha Laghubitta Bittiya Sanstha Limited",
"NFS": "Nepal Finance Ltd.",
"NGPL": "Ngadi Group Power Ltd.",
"NHDL": "Nepal Hydro Developers Ltd.",
"NHPC": "National Hydro Power Company Limited",
"NICA": "NIC Asia Bank Ltd.",
"NICL": "Nepal Insurance Co. Ltd.",
"NICLBSL": "NIC ASIA Laghubitta Bittiya Sanstha Limited",
"NIFRA": "Nepal Infrastructure Bank Limited",
"NIL": "Neco Insurance Limited",
"NIMB": "Nepal Investment Mega Bank Limited",
"NLG": "NLG Insurance Company Ltd.",
"NLIC": "Nepal Life Insurance Co. Ltd.",
"NLICL": "National Life Insurance Co. Ltd.",
"NMB": "NMB Bank Limited",
"NMBMF": "NMB Microfinance Bittiya Sanstha Ltd.",
"NMFBS": "National Laghubitta Bittiya Sanstha Limited",
"NMIC": "Nepal Micro Insurance Company Limited",
"NMLBBL": "Nerude Mirmire Laghubitta Bittiya Sanstha Limited",
"NRIC": "Nepal Reinsurance Company Limited",
"NRM": "Nepal Republic Media Limited",
"NRN": "NRN Infrastructure and Development Limited",
"NTC": "Nepal Doorsanchar Company Limited",
"NUBL": "Nirdhan Utthan Laghubitta Bittiya Sanstha Limited",
"NWCL": "Nepal Warehousing Company Limited",
"NYADI": "Nyadi Hydropower Limited",
"OHL": "Oriental Hotels Limited",
"OMPL": "Om Megashree Pharmaceuticals Limited",
"PCBL": "Prime Commercial Bank Ltd.",
"PFL": "Pokhara Finance Ltd.",
"PHCL": "Peoples Hydropower Company Limited",
"PMHPL": "Panchakanya Mai Hydropower Ltd",
"PMLI": "Prabhu Mahalaxmi Life Insurance Limited",
"PPCL": "Panchthar Power Compant Limited",
"PPL": "People's Power Limited",
"PRIN": "Prabhu Insurance Ltd.",
"PROFL": "Progressive Finance Limited",
"PRVU": "Prabhu Bank Limited",
"PURE": "Pure Energy Limited",
"RADHI": "Radhi Bidyut Company Ltd",
"RAWA": "Rawa Energy Development Limited",
"RBCL": "Rastriya Beema Company Limited",
"RFPL": "River Falls Power Limited",
"RHGCL": "Rapti Hydro And General Construction Limited",
"RHPL": "RASUWAGADHI HYDROPOWER COMPANY LIMITED",
"RIDI": "Ridi Power Company Limited",
"RLFL": "Reliance Finance Ltd.",
"RNLI": "Reliable Nepal Life Insurance Limited",
"RSDC": "RSDC Laghubitta Bittiya Sanstha Ltd.",
"RSML": "Reliance Spinning Mills Limited",
"RURU": "Ru Ru Jalbidhyut Pariyojana Limited",
"SABBL": "Salapa Bikas Bank Limited",
"SADBL": "Shangrila Development Bank Ltd.",
"SAGAR": "Sagar Distillery Limited",
"SAHAS": "Sahas Urja Limited",
"SAIL": "Shreenagar Agritech Industries Limited",
"SALICO": "Sagarmatha Lumbini Insurance Co. Limited",
"SANIMA": "Sanima Bank Limited",
"SANVI": "Sanvi Energy Limited",
"SAPDBL": "Saptakoshi Development Bank Ltd",
"SARBTM": "Sarbottam Cement Limited",
"SBI": "Nepal SBI Bank Limited",
"SBL": "Siddhartha Bank Limited",
"SCB": "Standard Chartered Bank Limited",
"SFCL": "Samriddhi Finance Company Limited",
"SGHC": "Swet-Ganga Hydropower & Construction Limited",
"SGIC": "Sanima GIC Insurance Limited",
"SHEL": "Singati Hydro Energy Limited",
"SHINE": "Shine Resunga Development Bank Ltd.",
"SHIVM": "SHIVAM CEMENTS LTD",
"SHL": "Soaltee Hotel Limited",
"SHLB": "Shrijanshil Laghubitta Bittiya Sanstha Limited",
"SHPC": "Sanima Mai Hydropower Ltd.",
"SICL": "Shikhar Insurance Co. Ltd.",
"SIFC": "Shree Investment Finance Co. Ltd.",
"SIKLES": "Sikles Hydropower Limited",
"SINDU": "Sindhu Bikash Bank Ltd",
"SJCL": "SANJEN JALAVIDHYUT COMPANY LIMITED",
"SJLIC": "SuryaJyoti Life Insurance Company Limited",
"SKBBL": "Sana Kisan Bikas Laghubitta Bittiya Sanstha Limited",
"SLBBL": "Swarojgar Laghubitta Bittiya Sanstha Ltd.",
"SLBSL": "Samudayik Laghubitta Bittiya Sanstha Limited",
"SMATA": "Samata Gharelu Laghubitta Bittiya Sanstha Limited",
"SMB": "Support Microfinance Bittiya Sanstha Ltd.",
"SMFBS": "Swabhimaan Laghubitta Bittiya Sanstha Limited",
"SMH": "Super Mai Hydropower Limited",
"SMHL": "Super Madi Hydropower Limited",
"SMJC": "Sagarmatha Jalabidhyut Company Limited",
"SMPDA": "Sampada Laghubitta Bittiya Sanstha Limited",
"SNLI": "Sun Nepal Life Insurance Company Limited",
"SONA": "Sonapur Minerals And Oil Limited",
"SPC": "Samling Power Company Limited",
"SPDL": "Synergy Power Development Ltd.",
"SPHL": "Sayapatri Hydropower Limited",
"SPIL": "Siddhartha Premier Insurance Limited",
"SPL": "Shuvam Power Limited",
"SRLI": "Sanima Reliance Life Insurance Limited",
"SSHL": "Shiva Shree Hydropower Ltd",
"STC": "Salt Trading Corporation",
"SWASTIK": "Swastik Laghubitta Bittiya Sanstha Limited",
"SWBBL": "Swabalamban Laghubitta Bittiya Sanstha Limited",
"SWMF": "Suryodaya Womi Laghubitta Bittiya Sanstha Limited",
"SYPNL": "SY Panel Nepal Limited",
"TAMOR": "Sanima Middle Tamor Hydropower Limited",
"TPC": "Terhathum Power Company Limited",
"TRH": "Taragaon Regency Hotel Limited",
"TSHL": "Three Star Hydropower Limited",
"TTL": "Trade Tower Limited",
"TVCL": "Trishuli Jal Vidhyut Company Limited",
"UAIL": "United Ajod Insurance Limited",
"UHEWA": "Upper Hewakhola Hydropower Company Limited",
"ULBSL": "Upakar Laghubitta Bittiya Sanstha Limited",
"ULHC": "Upper Lohore Khola Hydropower Company Limited",
"UMHL": "United Modi Hydropower Ltd.",
"UMRH": "United IDI Mardi RB Hydropower Limited.",
"UNHPL": "Union Hydropower Limited",
"UNL": "Unilever Nepal Limited",
"UNLB": "Unique Nepal Laghubitta Bittiya Sanstha Limited",
"UPCL": "UNIVERSAL POWER COMPANY LTD",
"UPPER": "Upper Tamakoshi Hydropower Ltd",
"USHEC": "Upper Solu Hydro Electric Company Limited",
"USHL": "Upper Syange Hydropower Limited",
"USLB": "Unnati Sahakarya Laghubitta Bittiya Sanstha Limited",
"VLBS": "Vijaya laghubitta Bittiya Sanstha Ltd.",
"VLUCL": "Vision Lumbini Urja Company Limited",
"WNLB": "Wean Nepal Laghubitta Bittiya Sanstha Limited",
}

# Data sources
DATA_SOURCES = {
    "merolagani": "https://merolagani.com/CompanyDetail.aspx?symbol={symbol}",
    "sharesansar_company": "https://www.sharesansar.com/company/{symbol}",
    "sharesansar_today": "https://www.sharesansar.com/today-share-price",
    "nepse_index": "https://www.sharesansar.com/index-history-data",
}

# Output paths
OUTPUT_DIR = "../data/company"
LOGS_DIR = "../logs"

# Scraping config
REQUEST_DELAY = 1.5     # seconds between requests (be polite)
REQUEST_TIMEOUT = 15    # seconds
MAX_RETRIES = 3

# CSV column order
CSV_COLUMNS = [
    "Date",
    "Open",
    "High",
    "Low",
    "Close",
    "Change",
    "Percent_Change",
    "Volume",
    "Turnover",
]
